import { BookData } from '@/types/indicator';

/**
 * Exemplo de como criar um book com diferentes números de indicadores
 * Os books podem ter de 1 a 6 indicadores
 */

export const bookWith2Indicators: BookData = {
  indicators: [
    {
      id: '1',
      name: 'NPS - Net Promoter Score',
      unit: '%',
      direction: 'up',
      editable: true,
      accumulated: {
        meta: 85,
        real: 90,
        percentage: 106,
      },
      months: {
        jan: { meta: 85, real: 88, percentage: 104 },
        feb: { meta: 85, real: 90, percentage: 106 },
        mar: { meta: 85, real: 92, percentage: 108 },
        apr: { meta: 85, real: 89, percentage: 105 },
        may: { meta: 85, real: 91, percentage: 107 },
        jun: { meta: 85, real: 90, percentage: 106 },
        jul: { meta: 85, real: 0, percentage: 0 },
        aug: { meta: 85, real: 0, percentage: 0 },
        sep: { meta: 85, real: 0, percentage: 0 },
        oct: { meta: 85, real: 0, percentage: 0 },
        nov: { meta: 85, real: 0, percentage: 0 },
        dec: { meta: 85, real: 0, percentage: 0 },
      },
    },
    {
      id: '2',
      name: 'Tempo de Resposta',
      unit: 'H$',
      direction: 'down',
      editable: true,
      accumulated: {
        meta: 24,
        real: 18,
        percentage: 75,
      },
      months: {
        jan: { meta: 24, real: 22, percentage: 92 },
        feb: { meta: 24, real: 20, percentage: 83 },
        mar: { meta: 24, real: 18, percentage: 75 },
        apr: { meta: 24, real: 17, percentage: 71 },
        may: { meta: 24, real: 16, percentage: 67 },
        jun: { meta: 24, real: 15, percentage: 63 },
        jul: { meta: 24, real: 0, percentage: 0 },
        aug: { meta: 24, real: 0, percentage: 0 },
        sep: { meta: 24, real: 0, percentage: 0 },
        oct: { meta: 24, real: 0, percentage: 0 },
        nov: { meta: 24, real: 0, percentage: 0 },
        dec: { meta: 24, real: 0, percentage: 0 },
      },
    },
  ],
};

export const bookWith6Indicators: BookData = {
  indicators: [
    {
      id: '1',
      name: 'Receita Mensal',
      unit: 'R$',
      direction: 'up',
      editable: true,
      accumulated: {
        meta: 1200000,
        real: 1350000,
        percentage: 113,
      },
      months: {
        jan: { meta: 100000, real: 110000, percentage: 110 },
        feb: { meta: 100000, real: 115000, percentage: 115 },
        mar: { meta: 100000, real: 112000, percentage: 112 },
        apr: { meta: 100000, real: 113000, percentage: 113 },
        may: { meta: 100000, real: 114000, percentage: 114 },
        jun: { meta: 100000, real: 116000, percentage: 116 },
        jul: { meta: 100000, real: 0, percentage: 0 },
        aug: { meta: 100000, real: 0, percentage: 0 },
        sep: { meta: 100000, real: 0, percentage: 0 },
        oct: { meta: 100000, real: 0, percentage: 0 },
        nov: { meta: 100000, real: 0, percentage: 0 },
        dec: { meta: 100000, real: 0, percentage: 0 },
      },
    },
    {
      id: '2',
      name: 'Novos Clientes',
      unit: '#',
      direction: 'up',
      editable: true,
      accumulated: {
        meta: 120,
        real: 145,
        percentage: 121,
      },
      months: {
        jan: { meta: 20, real: 25, percentage: 125 },
        feb: { meta: 20, real: 24, percentage: 120 },
        mar: { meta: 20, real: 23, percentage: 115 },
        apr: { meta: 20, real: 24, percentage: 120 },
        may: { meta: 20, real: 25, percentage: 125 },
        jun: { meta: 20, real: 24, percentage: 120 },
        jul: { meta: 20, real: 0, percentage: 0 },
        aug: { meta: 20, real: 0, percentage: 0 },
        sep: { meta: 20, real: 0, percentage: 0 },
        oct: { meta: 20, real: 0, percentage: 0 },
        nov: { meta: 20, real: 0, percentage: 0 },
        dec: { meta: 20, real: 0, percentage: 0 },
      },
    },
    {
      id: '3',
      name: 'Taxa de Conversão',
      unit: '%',
      direction: 'up',
      editable: true,
      accumulated: {
        meta: 15,
        real: 18,
        percentage: 120,
      },
      months: {
        jan: { meta: 15, real: 17, percentage: 113 },
        feb: { meta: 15, real: 18, percentage: 120 },
        mar: { meta: 15, real: 19, percentage: 127 },
        apr: { meta: 15, real: 18, percentage: 120 },
        may: { meta: 15, real: 17, percentage: 113 },
        jun: { meta: 15, real: 19, percentage: 127 },
        jul: { meta: 15, real: 0, percentage: 0 },
        aug: { meta: 15, real: 0, percentage: 0 },
        sep: { meta: 15, real: 0, percentage: 0 },
        oct: { meta: 15, real: 0, percentage: 0 },
        nov: { meta: 15, real: 0, percentage: 0 },
        dec: { meta: 15, real: 0, percentage: 0 },
      },
    },
    {
      id: '4',
      name: 'Churn Rate',
      unit: '%',
      direction: 'down',
      editable: true,
      accumulated: {
        meta: 5,
        real: 3,
        percentage: 60,
      },
      months: {
        jan: { meta: 5, real: 4, percentage: 80 },
        feb: { meta: 5, real: 3, percentage: 60 },
        mar: { meta: 5, real: 3, percentage: 60 },
        apr: { meta: 5, real: 2, percentage: 40 },
        may: { meta: 5, real: 3, percentage: 60 },
        jun: { meta: 5, real: 3, percentage: 60 },
        jul: { meta: 5, real: 0, percentage: 0 },
        aug: { meta: 5, real: 0, percentage: 0 },
        sep: { meta: 5, real: 0, percentage: 0 },
        oct: { meta: 5, real: 0, percentage: 0 },
        nov: { meta: 5, real: 0, percentage: 0 },
        dec: { meta: 5, real: 0, percentage: 0 },
      },
    },
    {
      id: '5',
      name: 'Satisfação do Cliente',
      unit: '%',
      direction: 'up',
      editable: true,
      accumulated: {
        meta: 90,
        real: 93,
        percentage: 103,
      },
      months: {
        jan: { meta: 90, real: 92, percentage: 102 },
        feb: { meta: 90, real: 93, percentage: 103 },
        mar: { meta: 90, real: 94, percentage: 104 },
        apr: { meta: 90, real: 93, percentage: 103 },
        may: { meta: 90, real: 92, percentage: 102 },
        jun: { meta: 90, real: 94, percentage: 104 },
        jul: { meta: 90, real: 0, percentage: 0 },
        aug: { meta: 90, real: 0, percentage: 0 },
        sep: { meta: 90, real: 0, percentage: 0 },
        oct: { meta: 90, real: 0, percentage: 0 },
        nov: { meta: 90, real: 0, percentage: 0 },
        dec: { meta: 90, real: 0, percentage: 0 },
      },
    },
    {
      id: '6',
      name: 'Produtividade da Equipe',
      unit: '#',
      direction: 'up',
      editable: true,
      accumulated: {
        meta: 500,
        real: 580,
        percentage: 116,
      },
      months: {
        jan: { meta: 500, real: 520, percentage: 104 },
        feb: { meta: 500, real: 540, percentage: 108 },
        mar: { meta: 500, real: 560, percentage: 112 },
        apr: { meta: 500, real: 580, percentage: 116 },
        may: { meta: 500, real: 600, percentage: 120 },
        jun: { meta: 500, real: 580, percentage: 116 },
        jul: { meta: 500, real: 0, percentage: 0 },
        aug: { meta: 500, real: 0, percentage: 0 },
        sep: { meta: 500, real: 0, percentage: 0 },
        oct: { meta: 500, real: 0, percentage: 0 },
        nov: { meta: 500, real: 0, percentage: 0 },
        dec: { meta: 500, real: 0, percentage: 0 },
      },
    },
  ],
};

